### PR TITLE
Feature SI-2631 Remove Update Endpoint

### PR DESCRIPTION
**Pull request by zer0stars**
# Proposed Changes
Remove autopi update task endpoints
### Impacted Routes

/aftermarket/device/by-serial/{serial}/update
### Caveats
Can't be merged until the mobile release.

### CODE REVIEW

**Comment by zer0stars** [comment]
Mobile is set to deprecate this endpoint in the next release(1.14.0)
https://github.com/DIMO-Network/dimo-driver/pull/1005

**Comment by elffjs** [comment]
Did some more deletion in #336. Too much?

**Comment by elffjs** [comment]
1.14.0 (and beyond) is out. Can we start merging these?

**Comment by elffjs** [comment]
I still see calls

image

**Comment by elffjs** [comment]
Jade says it's okay, let's say it's okay.

**Pull request merged**
